Adicionando workflow comentarios
npdscodes/mural-api pull request #8
Opened 2016-10-11 14:29 UTC by Marlysson

Adicionando parte relacionada à interação na postagem.
- Adicionado testes
- Adicionado restrições para respostas não receberem respostas.

2016-10-11 14:29 UTC, Marlysson commented
À verificar : 
> Obter o usuário logado para associá-lo à resposta criada. Pelo modelo não tem como capturar a requisição , por enquanto está somente no modelo, quando tiver requisições poderá capturar o request.user.

2016-10-11 14:30 UTC, Marlysson commented
No github a identação ficou desorganizada.. vou arrumar..

2016-10-11 14:31 UTC, rogerio410 commented
Usando qual IDE?

2016-10-11 14:31 UTC, Marlysson commented
Sublime, está com tab size : 4.

2016-10-11 14:34 UTC, rogerio410 commented
Então tá Tab ou 4 Espaço. Tem que ficar espaços de fato de acordo com a PEP-8.. [PEP-8: Indentation](https://www.python.org/dev/peps/pep-0008/#indentation)

2016-10-11 14:41 UTC, Marlysson commented
Corrigido indentação do editor.

2016-10-11 14:43 UTC, Marlysson commented
Lembrando que com esse workflow validado passarei para a outra parte, acho que por partes pode ser interessante para avaliar..

2016-10-11 17:52 UTC, rogerio410 commented
@Marlysson revisando seu código. Vi aqui que adotou um forma de alinhar os fields. Pycharm me faz um alerta: "PEP-8: multiple spaces before operator". Está seguindo alguma prática?

2016-10-11 17:57 UTC, rogerio410 commented
@Marlysson Pycharm alerta outro PEP-8 Alert. : "missing whitespace after ','"  `(max_length=10,default=PAI,blank=False,`

2016-10-11 17:57 UTC, Marlysson commented
Só questão de organização e alinhamento mesmo.. A pep8 provável que recomende de 1/2 espaços antes e depois.. Vou baixar da uma geral na pep8 e baixar uns plugins de linter pra ajudar..

2016-10-11 17:58 UTC, Marlysson commented
Sobre o outro erro.. Vou adicionar espaços depois das virgulas.. Comecei nos importa mas no código ainda não.. Vou arrumar :+1:

2016-10-11 18:07 UTC, rogerio410 requested changes
@Marlysson sobre a operação responder: O que achas de ao tentar responder uma resposta invés de disparar um exception o software recebesse a resposta com mais uma resposta do comentário Pai? O Facebook é assim.

2016-10-11 18:56 UTC, Marlysson commented
Sim , pensei nisso também, lá eles identificam a resposta respondida com uma marcação do user lá da resposta que ta querendo responder.. Podia ter uma forma tbm de indicar a resposta.. 

Pode sim, perfeitamente.. Teria o caso de indicar a resposta que ta sendo respondida ou só adicionar mesmo..?

2016-10-11 18:58 UTC, rogerio410 commented
Não entendi. Mas poderia ficar transparente para o usuário. Ele ao tentar responder um comentário PAI A incluiria como FILHO F. Ao tentar responder FILHO F incluiria como FILHO G do PAI A. hehehe

2016-10-11 19:19 UTC, Marlysson commented
Sim , entendi..vou ja commitar essa parte.. 

Pensei aqui e ficaria meio complicado.. E o resultado só veria mesmo na APP..

Mas o facebook marca a pessoa de uma resposta quando da reply em uma resposta.. Só isso :D

Yagni :D kk .

2016-10-11 21:34 UTC, Marlysson commented
@rogerio410 adicionei o que falou com relação à adicionar mais respostas.. e não mais gerar erro..

2016-10-13 12:40 UTC, rogerio410 commented
Ok @Marlysson. Ei essa atributo tipo poderia ser CHOICE? para restringir a alguma opções, no caso PAI e FILHO mais ou meno assim: [oscar](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/abstract_models.py) 
```python
 STANDALONE, PARENT, CHILD = 'standalone', 'parent', 'child'
    STRUCTURE_CHOICES = (
        (STANDALONE, _('Stand-alone product')),
        (PARENT, _('Parent product')),
        (CHILD, _('Child product'))
    )
    structure = models.CharField(
        _("Product structure"), max_length=10, choices=STRUCTURE_CHOICES,
        default=STANDALONE)
```

2016-10-13 12:44 UTC, Marlysson commented
Até pensei em usar o choices sim , mas ele não seria para  ocaso de renderização em formulários ? Visto que o tipo será definido em runtime baseado se está respondendo um pai ou filho..

Vendo aqui.. interessante o uso.. vou já adicionar..

Mais alguma coisa no código..

2016-10-13 12:47 UTC, rogerio410 commented
Teria que ver se quando um campo é choice ele bloqueia ou não à estas opções.

2016-10-13 12:51 UTC, rogerio410 approved these changes

2016-10-13 12:52 UTC, rogerio410 commented
@Marlysson teríamos que primeiro atualizar este branch com o atual master? O github informa que não há conflito. Poderíamos fazer o merge direto também.

2016-10-13 12:55 UTC, Marlysson commented
Quando clonei eu me baseei no master com os pull requests do ayron feitos ( só models ) .. mas ainda sem as que ele adicionou dos endpoints.. Acho que terei que dá um pull aqui e fazer um novo commit para esse branch com o código atualizado.

2016-10-13 12:56 UTC, Marlysson commented
Se fizer o merge por aqui eu posso atualizar depois no meu ou só deletar o branch local e a próxima tarefa criar o branch baseado na master.

2016-10-13 12:59 UTC, rogerio410 commented
Cara como Mostra que não há conflito. Podemos Fazer o merge aqui, sem problemas. Se tivesse o correto seria atualizar primeiro o este branch com o atual master (fetch & merge) e em seguida o merge de volta.

2016-10-13 13:00 UTC, rogerio410 commented
@Marlysson posso fazer o merge ou ainda tem algum detalhe sobre a intenção/objetivo deste Branch?

2016-10-13 13:03 UTC, Marlysson commented
Até agr blz.

2016-10-13 13:04 UTC, rogerio410 commented
E o Choice vai botar?

2016-10-13 13:06 UTC, Marlysson commented
Ok então, colocar aqui nessa logo. Só um min.

2016-10-13 13:38 UTC, Marlysson commented
@rogerio410 adicionado choices e uns testes relacionados ao comportamento do ```on_delete```

2016-10-13 14:01 UTC, merged